### ISSUE TITLE
Consumer Example

### ISSUE THREAD

**Issue by websirnik** [bernardphp/bernard#100]
I'm trying to figure out the proper way to use Bernard for consuming messages. I have the following code(using IronMQ driver):

```
    $router = new ContainerAwareRouter( $container, array( 'UpdatePostSnapshots' => 'update_snapshots_service' ) );
    $consumer = new Consumer( $router, new MiddlewareBuilder() );
    $consumer->consume( $queueFactory->create( 'post-update-snapshots-msg' ), array( 'max-runtime' => 900 ) );
```

I run it as a custom console command in Symfony. It works well, however IronMQ dashboard shows several thousand API requests within a few minutes(just for one consumed message).

How do I optimize this, so the worker would not go crazy over IronMQ with million requests a day for not a large queue.

**Comment by sagikazarmark** [comment]
Looks like you sorted it out.
