### ISSUE TITLE
RabbitMQ driver

### ISSUE THREAD

**Issue by estahn** [bernardphp/bernard#115]
Would be great so see a RabbitMQ driver implemented (https://www.rabbitmq.com/).

**Comment by acrobat** [comment]
I think this issue can be closed as a rabbitmq/amqp driver was added in #174

**Comment by acrobat** [comment]
Maybe not the right place to ask, but when do you accept a stable release @henrikbjorn? It looks like the docs are a bit out dated but I will send a PR for it soon!

**Comment by henrikbjorn** [comment]
@acrobat when the docs and a changelog have been created. I am currently busy with work and it sadly does not allow me much time.
