### ISSUE TITLE
Fix property visibility

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#132]
Acoording to discussion with @henrikbjorn visibility should be fixed.

**Comment by sagikazarmark** [comment]
What was this exactly? Make everything final/private by default?

**Comment by acrobat** [comment]
Is this something we should check over the whole lib or did you had some specific classes? Ideally we should pick this up before releasing a stable release

**Comment by sagikazarmark** [comment]
Yes, the whole library should be scanned in form of a generic code review IMO.

**Comment by sagikazarmark** [comment]
This is happening, will be part of generic review and refactoring.
