### ISSUE TITLE
Increase minimum php version

### ISSUE THREAD

**Issue by henrikbjorn** [bernardphp/bernard#163]
To atleast 5.4

**Comment by sagikazarmark** [comment]
Does it mean that `[]` can be used instead of `array()`?

**Comment by henrikbjorn** [comment]
Yes

**Comment by sagikazarmark** [comment]
Not sure what you mean.

**Comment by henrikbjorn** [comment]
Increasing the required version in composer.json for bernard.

**Comment by sagikazarmark** [comment]
Ah, I see. I was rather curious about if the coding style would change to use the PHP 5.4 array notation instead of the "old" one.

**Comment by henrikbjorn** [comment]
I think ill change it everywhere when i decide on which version.

**Comment by Baachi** [comment]
:+1: for set the minimum php version to 5.4.

**Comment by TomasVotruba** [comment]
This might also help to decide http://seld.be/notes/my-view-of-php-version-adoption

**Comment by sagikazarmark** [comment]
Actually it is already decided. It can be closed.

**Comment by TomasVotruba** [comment]
:+1:
