### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#172]
`Message queue implemented in PHP with Redis as a backend.`

This isn't really right anymore, is it?

**Comment by mpdude** [comment]
Just came across this as well when I saw your change in the other PR :)

**Comment by sagikazarmark** [comment]
Other PR?

**Comment by mpdude** [comment]
The change to composer.json in #171.

**Comment by henrikbjorn** [comment]
Seems like this can be closed.
