### ISSUE TITLE
Create a new tag/release from master

### ISSUE THREAD

**Issue by rjd22** [bernardphp/bernard#175]
We want to use bernard in combination with the bundle and pheanstalk but we can't right now because bernard has no tag of the pheanstalk implementation. Can someone tags benard with the pheanstalk implementation?

**Comment by henrikbjorn** [comment]
Problem with this is that the documentaiton is not updated and because of the chagnes it would have to be 2.0.0 unless you can live with a 2.0.0-alpha release?

**Comment by henrikbjorn** [comment]
Tagged a 1.1.0

**Comment by ruudk** [comment]
Any news? We've been running `1.0.0-alpha2` for a while now without any problems.

**Comment by rjd22** [comment]
@henrikbjorn I think we can close this now since it tagged a few more releases.
