### ISSUE TITLE
Add phpunit/phpunit to require-dev

### ISSUE THREAD

**Issue by elazar** [bernardphp/bernard#178]
Since Bernard uses PHPUnit for its test suite, it seems like `phpunit/phpunit` should be included in the `require-dev` section of its `composer.json` file.

**Comment by henrikbjorn** [comment]
PHPUnit will not be added to the composer.json file. PHPUnit is a standalone application that is used for testing and as such it should be installed standalone. This also reduces the risk of phpunit dependencies interfering with Bernard's.

Thanks for the suggesting :)
