### ISSUE TITLE
ObjectResolver doesn't exist

### ISSUE THREAD

**Issue by elazar** [bernardphp/bernard#180]
The ["Consuming Messages"](https://github.com/bernardphp/bernard/blob/master/doc/consuming.rst) section of the docs references `Bernard\ServiceResolver\ObjectResolver`. Neither the containing sub-namespace nor the class itself exist. The closest equivalents I can find are [`\Bernard\Driver`](https://github.com/bernardphp/bernard/blob/master/src/Driver.php) and [its implementations](https://github.com/bernardphp/bernard/tree/master/src/Router).

**Comment by henrikbjorn** [comment]
Hey Elazar

The master branch uses the term "Router" for that part `https://github.com/bernardphp/bernard/blob/master/src/Router/SimpleRouter.php`. So it just needs to be updated for master, also it needs an EventDispatcher now.

**Comment by elazar** [comment]
Yeah, I think I've got it figured out. Mostly filing the issue so that the documentation being outdated is visible. Thanks.

**Comment by sagikazarmark** [comment]
As far as I can see the documentation has been updated.
