### ISSUE TITLE
Current producer/consumer implementation is limited

### ISSUE THREAD

**Issue by elazar** [bernardphp/bernard#181]
The current producer/consumer model is based on the assumption that messages are published with a specified envelope name that contributes to how they are routed; more specifically, that they are routed to a queue based on that envelope name and that a separate consumer process is maintained per queue.

This is a very limiting architecture in infrastructures like Heroku, where I may only want to operate a single worker process across all queues because limited traffic doesn't warrant a separate process per queue.

It is possible to work around this limitation by sending messages to a single queue, extending the router, and having it resolve the receiver differently based on some attribute other than the envelope name, such as a message argument.

However, this solution is just that: a work-around. It would be nice if this was something the Bernard architecture supported natively through a more interface-driven design with consumers.

**Comment by henrikbjorn** [comment]
Hey @elazar 

Do you have a specific change in mind? Currently the only way is to make sure you use the second argument to the produce method, and specify a specific queue, or use an event listener to change the Envelope before they are persisted to the backend.

**Comment by elazar** [comment]
If terms of a non-BC-breaking change, possibly modify `Consumer->consume()` to be like so:

```php
    public function consume($queues, array $options = [])
    {
        $this->bind();
        if ($queues instanceof Queue) {
            $queues = [$queues];
        }
        foreach ($queues as $queue) {
            while ($this->tick($queue, $options)) {
                // NO op
            }
        }
    }
```

This would allow multiple queues to be checked in a single process without compromising the existing ability to have a single queue checked per process. I'm not sure if that would be sufficient to cover most use cases, but it would cover more than the current implementation.

**Comment by henrikbjorn** [comment]
That could be done, but that raises some questions:

1. Should the first queue be drained before checking the next?
2. Is it okay to increase latency based on the number of queues in your list?

**Comment by elazar** [comment]
1. I don't think so because I believe that could lead to queue [starvation](https://en.wikipedia.org/wiki/Starvation_(computer_science)) given a queue with sufficient traffic.
2. I think it is just because it leaves it up to the user as to which and how many queues to use per process. If I have few queues that receive few messages, it makes more sense to use a single process. By contrast, if I have a queue that receives a lot of traffic, I still have the option of moving it to its dedicated own process and leaving the other queues with less traffic in a shared process.

The change I'm suggesting merely makes it possible to have multiple queues share a process. As I said, this is merely the least invasive change to accomplish that objective.

Long-term, it may make more sense to establish a minimal common interface for consumers, implement multiple core consumers for the more common use cases we've discussed here, and allow third-party consumers to be developed for other use cases.

**Comment by henrikbjorn** [comment]
I would gladly accpet at PR against master, assuming it does round robin each of the queues

**Comment by elazar** [comment]
Cool. So far as I can tell from the existing source code, the implementation I've suggested above should do round robin. Just starting my work day here, but I'll try to work on a PR this evening.

**Comment by elazar** [comment]
@henrikbjorn #182 is the PR you requested if you'd like to give it a look.

**Comment by henrikbjorn** [comment]
Was thinking about this, would it be possible to create a ChainQueue or RoundRobinQueue, this could be created by the Command instead of the consumer, then we dont have to update the api for the Consumer?

Sorry for the long answers :/

**Comment by elazar** [comment]
@henrikbjorn I've created #183 to add a potential `RoundRobinQueue` implementation. Assuming it meets with your approval, how do you see use of this being implemented in `ConsumeCommand`? Adding support for specifying multiple queues (e.g. as a comma-delimited string) in the existing `--queue` parameter? Here's an example of how that could work:

```php
public function execute(InputInterface $input, OutputInterface $output)
{
    $queues = explode(',', $input->getArgument('queue'));
    if (count($queues) > 1) {
        $subqueues = array_map([$this->queues, 'create'], $queues);
        $queue = new RoundRobinQueue($subqueues);
    } else {
        $queue = $this->queues->create(array_shift($queues));
    }
    $this->consumer->consume($queue, $input->getOptions());
}
```

**Comment by elazar** [comment]
@henrikbjorn My last comment contained a question about if / how this should be implemented in `ConsumeCommand`. It's good that #188 has been merged, but there's no way to access the functionality it added from command line. Should I file a separate issue / PR for this?

**Comment by henrikbjorn** [comment]
@elazar yeah it should be wrapped in the Consume command. a PR would be great :+1:
