### ISSUE TITLE
What happened to bernardphp.com?

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#189]

**Comment by ruudk** [comment]
It expired, and now somebody else took it. Docs are up at http://bernard.readthedocs.org/

**Comment by henrikbjorn** [comment]
If somebody comes up with a good idea for a domain, i will gladly purchase it.

**Comment by sagikazarmark** [comment]
bernardphp.io and bernardphp.net are both free:

https://www.namecheap.com/domains/registration/results.aspx?domain=bernardphp.io

**Comment by henrikbjorn** [comment]
never really liked the php part of the name.

**Comment by sagikazarmark** [comment]
Me neither, but bernard is not a fantasy name, very likely most of bernard.TLD will not be available. Checking though

**Comment by henrikbjorn** [comment]
We could use the `flint` name and just have bernard.flint.xx or something ? or is that a bad idea/

**Comment by sagikazarmark** [comment]
Hm, I think bernard is big enough to have it under a custom domain.

Some free bernard domains:

bernard.pw (professional web)
bernard.software

But these are not the best though....

**Comment by henrikbjorn** [comment]
The js community have `{project}.js.org`, why doesn't php have that :/

**Comment by sagikazarmark** [comment]
Yeah, would be nice.

**Comment by sagikazarmark** [comment]
php.group
php.ong

domains are available, but I guess it's not the same :(
