### ISSUE TITLE
DoctrineDriver - Use UUID instead of autoincrement ID's

### ISSUE THREAD

**Issue by ruudk** [bernardphp/bernard#204]
We use the DoctrineDriver and every now and then we'll hit a dead lock. 

I think the reason for this is that the DoctrineDriver creates a `bernard_messages` table where the `id` is autoincrement. 

This locks the table every time an insert is executed.

I think we should use UUID's and get rid of the autoincrement ids. The only problem is that we need to sort based on date + microtime.

**Comment by henrikbjorn** [comment]
In a project at work we use something like this http://engineering.custommade.com/simpleflake-distributed-id-generation-for-the-lazy/ for generating integer based ids that is sorteable like auto increments. Cannot share our integration sadly.

**Comment by henrikbjorn** [comment]
Would you be up to work on this? We could make it an external bernard library.

**Comment by ruudk** [comment]
Well, for me, the UUID4 + microtime approach is good enough. Maybe I can submit that as a PR?

**Comment by henrikbjorn** [comment]
Would be amount of time be different for the two implementations?

**Comment by ruudk** [comment]
What do you mean?

**Comment by henrikbjorn** [comment]
Implementing the "snowflake" thing vs. implementing the uuid v4 solution.

**Comment by sagikazarmark** [comment]
Dunno if it makes sense to have the two solutions in parallel. Maybe we can make it configurable? I could do it as part of the driver separation process #256

**Comment by holtkamp** [comment]
This might be interesting, performance / lock-wise:

- article: https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
- inspiration implementation: https://github.com/ramsey/uuid-doctrine
  - not sure if this can adopted/used easily, but might be worth trying to

**Comment by henrikbjorn** [comment]
I would much rather have the simpleflake implementation, as it is sortable by default etc.

**Comment by holtkamp** [comment]
>In a project at work we use something like this http://engineering.custommade.com/simpleflake-distributed-id-generation-for-the-lazy/ 

this page seems [down](https://github.com/SawdustSoftware/simpleflake/issues/9) 😢 
- Presentation here: http://akmanalp.com/simpleflake_presentation
- PHP implementation here: https://github.com/michaelcontento/simpleflake-php

**Comment by makmanalp** [comment]
Cross-linking discussion here: https://github.com/SawdustSoftware/simpleflake/issues/9

I don't know your exact requirements but one alternative approach is to do something like uuid1 (which has machine-id and time bits) and then reordering the bits so that the time stuff comes at the beginning, so it still sorts lexicographically.

**Comment by acrobat** [comment]
Shouldn't we keep this issue open and implement it while doing work on the drivers?
