### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ruudk** [bernardphp/bernard#207]
A new alpha was released 9 days ago. Are there any issues blocking a 1.0 release? :)

**Comment by henrikbjorn** [comment]
Mainly documentation and changelog. Also the RoundRobinQueue have had some difficulties.

**Comment by henrikbjorn** [comment]
And making sure Symfony 3 does not break anything.

**Comment by ruudk** [comment]
What needs to be changed on the docs? Maybe I can find some time for it. I really want a stable release so that I can change some other bundles depending on this :)

**Comment by henrikbjorn** [comment]
We need a Changelog from the 0.x releases up to alpha 1, i really wanted the docs to be rewritten, but that is a HUGE task, so just making sure the serializer stuff and event dispatcher stuff is up2date.

**Comment by acrobat** [comment]
I will try to jump in on the docs issue! I've implemented this lib in a project i'm currently on, so I now the new stable workflow quite well

**Comment by ruudk** [comment]
That would be awesome :)

**Comment by acrobat** [comment]
I've created #215 for the docs rewrite, so any feedback is welcome!

**Comment by danydev** [comment]
@henrikbjorn @ruudk Hey Guys, almost 1 year from the 1.0 alpha, are there plans to release it as stable? what's missing?

**Comment by henrikbjorn** [comment]
Ill look at doing it tomorrow 😊
søn. 11. dec. 2016 kl. 10.25 skrev danydev <notifications@github.com>:

**Comment by ruudk** [comment]
🙏🙏🙏

**Comment by danydev** [comment]
@henrikbjorn great, thank you.

ps: I think [this bug](https://github.com/bernardphp/bernard/pull/275) deserves a fix before 1.0.0 release

**Comment by henrikbjorn** [comment]
I went through some PR and pinged their author, so we don't have to do a 1.0.1 shortly after 1.0

**Comment by ruudk** [comment]
Any news? We are running `1.0.0-alpha4` in production without any issues.

**Comment by danydev** [comment]
@ruudk still not merged on master fix for #275 (i.e. #252) that prevents bernard to work with PostgreSQL

**Comment by henrikbjorn** [comment]
It needs to be rebased onto master and i don't currently have the time to do so.

**Comment by martinssipenko** [comment]
Any plans release 1.0 or at least a new alpha any time soon?

**Comment by sagikazarmark** [comment]
An alpha is coming.

/cc @acrobat

**Comment by acrobat** [comment]
A new alpha is released! See: https://github.com/bernardphp/bernard/releases/tag/v1.0.0-alpha5

**Comment by fedeisas** [comment]
Is there any way I can help to turn the last alpha into a stable version? I'm implementing a new project using Bernard and I'd love to contribute. Thanks!

**Comment by sagikazarmark** [comment]
Unfortunately there are quite a few design decisions left to make, so
tagging at this point is early IMO. I would say we should aim this year for
the stable, but nothing more concrete.

You can take a look at the open issues and contribute to the discussion.

2017. júl. 18. de. 4:08 ezt írta ("Fede Isas" <notifications@github.com>):
