### ISSUE TITLE
New release following 0.12 branch/line

### ISSUE THREAD

**Issue by davidreuss** [bernardphp/bernard#217]
Hi, #216 was merged and we need a proper release so we can update all our dependencies.

Not sure what the process is here, but we talked about it, and this is the followup issue :+1:

**Comment by acrobat** [comment]
I think if we can review/merge #215 and #206, then this library should be ready for a stable release (imo)

**Comment by henrikbjorn** [comment]
@acrobat the 0.12 release does not use the event dispatcher etc. So we need to make it a seperate release.

Havn't had time to review the two PR's yet.
