### ISSUE TITLE
Split up the driver interface

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#224]
In my opinion, there is too much responsibility in the Driver interface. For example not all queues allow to give information about itself (which can't be abstracted anyway), not all of them allow to create new or remove queues, etc. Therefore I think we should split up the Driver interface into several smaller one:
- The core driver interface should allow push/pop/ack which are necessary for the messaging itself
- The should be a driver supporting information retrieval (info, peek?, maybe separately?)
- There should be a driver which allows listing queues
- There should be a driver which allows creating/removing queues

This of course comes with complications in the implementation, however I think it would be better to put knowsledge (what a driver capable of) into abstraction instead of returning empty/default values. If a driver is not capable of something, why would you try to do that thing?

Looking forward to hear your feedback.

**Comment by sagikazarmark** [comment]
@henrikbjorn may I ask for your feedback on this one?

**Comment by sagikazarmark** [comment]
Separate driver responsibilities:

- Basic/Messaging: push/pop/ack messages
- Queue management: list/create/remove queue
- Counting messages in a queue (might belong to the previous one)
- Peeking
- Stats

These are all separate responsibilities and not all of the drivers support all of them. A default noop implementation might make sense and might be required in many cases, but instead of relying on meaningless empty values, we could rely on the driver's nature (namely implements and interface of not).

**Comment by sagikazarmark** [comment]
@henrikbjorn WDYT?

**Comment by henrikbjorn** [comment]
Not sure this is worth pursuing, currently the drivers are "internal" only, meaning the end user should not work with them directly.

**Comment by henrikbjorn** [comment]
but if it will clean up some code paths i am for it.

**Comment by sagikazarmark** [comment]
Well, after rethinking there is only one remaining thing that bugs me: it seems to be wrong to return an empty array in peek when the driver does not support peeking.

No-op code (like createQueue when manual creation is not necessary) is not that big problem after all.
