### ISSUE TITLE
Default message name

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#225]
Two years old, still one of my most linked article: http://verraes.net/2013/09/sensible-interfaces/

One of the points here (which I agree with) is that Default means nothing. Default what?

Although it is a default implementation, I think PlainMessage sounds better. WDYT?

**Comment by henrikbjorn** [comment]
:+1:

**Comment by davidsteinsland** [comment]
I am assuming this BC feature will stick around for some time then:
`class DefaultMessage extends PlainMessage {}`

?

**Comment by sagikazarmark** [comment]
Given there is no stable release, not sure if it is necessary.

**Comment by henrikbjorn** [comment]
It will if somebody does the PR for this :)

**Comment by davidsteinsland** [comment]
Although I agree @sagikazarmark, we're already using bernard in two different production environments already.. So, I would appreciate some form of semver.. (although semver *does* indicate that 0.y.z is non-stable until 1.0.0).

I guess it's up to @henrikbjorn :dancer:

**Comment by sagikazarmark** [comment]
Worst case scenario is to manually alias the class (or even do that in bernard?)

**Comment by sagikazarmark** [comment]
My point is that starting 1.0 with already deprecated features is not really a good communication of semver.

**Comment by davidsteinsland** [comment]
Worst case? `class DefaultMessage extends PlainMessage {}` should like an OK solution for releases up to, but not including, `1.0.0`.

As already stated, we're using bernard heavily, and we can provide much better testing of new versions if we don't have to fix our code for *every* release.

**Comment by sagikazarmark** [comment]
> Worst case?

I meant you can just add a `class_alias` somewhere at the beginning of your application. Problem solved :wink:

**Comment by sagikazarmark** [comment]
Well, I could imagine a solution, like maintaining BC until 1.0 (although as you also said, that's not semver).

**Comment by davidsteinsland** [comment]
Whaaa.... `class_alias` should *never* be a feature in production php.. It's acceptable for mocking, yes...
I could rant on this for some while.

**Comment by sagikazarmark** [comment]
Why? And how is it related to mocking? Not the best solution I admit that, but I don't see why it couldn't be a temporary one, even in production. (Many frameworks actually did it in the past, before DI started to spread)

**Comment by davidsteinsland** [comment]
Just the point that it doesn't get picked up by auto completions/code intels is a good enough reason for me to drop it. But anywho, it's not a big update for me to change `DefaultMessage` to `PlainMessage` anyways, as we have our own message containers (that just extends `DefaultMessage`). So it's maximum 10 updates.

I just remember when I updated our code base to match the newest bernard, with events.. That was a lot more work.

**Comment by sagikazarmark** [comment]
> I just remember when I updated our code base to match the newest bernard, with events.. That was a lot more work.

Well, yeah I can understand that. Kind of hard to work without a BC promise, but at this phase, it is also hard to have one.

**Comment by davidsteinsland** [comment]
Sooner, rather than later, bernard should be `1.0.0` anyways. If it keeps going non-stable for months to come, I would assume that people opt not to use it (for the reasons already mentioned).

This discussion can probably continue in another issue.

**Comment by henrikbjorn** [comment]
I would be happy to release a 1.0 as is. The only problem is that i don't use it much anymore myself. So if someone can convince me its a good enough ill tag a 1.0

**Comment by sagikazarmark** [comment]
I would not. :smile: 

Take a look at the list of issues and PRs. Many of them contain BC breaking stuff. Also, I would do some redesign regarding driver interfaces as mentioned in #224, etc.
