### ISSUE TITLE
Add suggestion of pcntl in composer.json 

### ISSUE THREAD

**Issue by davidsteinsland** [bernardphp/bernard#230]
... because it is used in `Consumer`. In versions `<= 1.0.0-alpha.2` the PCNTL extension is actually required, but it is not present in the `require` section either.

https://getcomposer.org/doc/04-schema.md#suggest

**Comment by davidsteinsland** [comment]
The error that caused me to create this issue was:
```
Fatal error:  Call to undefined function Bernard\pcntl_signal() in vendor/bernard/bernard/src/Consumer.php on line 165
```

I thought that the extension wasn't loaded, but after creating the issue I noticed that it was in fact loaded.
What causes PHP to complain is that the `pcntl_*()` functions are added to the `disable_functions` ini entry.

My dev server is an Ubuntu machine, where PHP is installed from the official ubuntu repo. 
This caveat should probably be mentioned somewhere.

**Comment by henrikbjorn** [comment]
I merged a PR the other day that checked for the functions (https://github.com/bernardphp/bernard/blob/master/src/Consumer.php#L170), is that enough or do we need a more extensive test for the availability of these functions?

**Comment by davidsteinsland** [comment]
That should work, but would be nice to get a suggestion as well. That way one can clearly see that ext-pcntl gives extra functionality.
