### ISSUE TITLE
DirectoryIterator::__construct() expects exactly 1 parameter, 2 given

### ISSUE THREAD

**Issue by luklub** [bernardphp/bernard#235]
Hi!
Seems that the only one parameter (the path of the directory to traverse) is expected by DirectoryIterator constructor in FlatFileDriver (https://github.com/bernardphp/bernard/blob/master/src/Driver/FlatFileDriver.php in line 32,  listQueues() method). Perhaps the FilesystemIterator should be used.

Edit:
I found this pull request https://github.com/bernardphp/bernard/pull/177. Maybe other iterator is better solution.

**Comment by henrikbjorn** [comment]
Feel free to open an updated PR and ill gladly merge it.
