### ISSUE TITLE
PHPAmqpDriver missing from 0.12.3

### ISSUE THREAD

**Issue by ghost** [bernardphp/bernard#242]
Hello everyone.
Package https://packagist.org/packages/bernard/bernard#0.12.3 features RabbitMQ-capabilities.
Using the package as described in the documentation, and entering phpamqp as the driver yields an exception in Symfony as it is not an allowed value.
Looking at /vendor/bernard/bernard/src/Bernard/Driver/ shows the abscence of PhpAmqpDriver.php .
Looking at the repository https://github.com/bernardphp/bernard/blob/master/src/Driver/PhpAmqpDriver.php shows that the file has been edited end of last year https://github.com/bernardphp/bernard/commit/5fec5b0098089091e28f563cbb93f295060db4c4 .

A composer require bernard/bernard installes bernard with version 0.12.3 as can be seen in the composer.json 

> ```
>    ... "bernard/bernard": "^0.12.3", ...
> ```

I assume that during the release of the package this file somehow did not make it into the release by accident.
Could you please update the released package as it would be a great library to use.

All requirements php-amqp, additional bundles, etc. have been installed and using a flat-file-configuration shows that bernard works, so it is not an issue with some configuration other than that the driver is missing from the directory and the definitions in the services.xml.

bernard is used using https://packagist.org/packages/bernard/bernard-bundle#1.1.2 , but the problem is most likely with the bernard-package itself.

The error with which Symfony failes

>  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
>     The value "phpamqp" is not allowed for path "bernard_bernard.driver". Permissible values: "file", "predis", "doctrine", "phpredis", "ironmq", "sqs"

**Comment by henrikbjorn** [comment]
This is a problem with the bundle. The bundle configuration does not allow phpamqp, feel free to open a PR against the bundle for this.

**Comment by sagikazarmark** [comment]
It has been solved here: https://github.com/bernardphp/BernardBundle/commit/de397d900f1e77df6eefff512f89cf9c17c5520e

**Comment by acrobat** [comment]
As @sagikazarmark mentioned this has been fixed!
