### ISSUE TITLE
Several methods are empty in PhpAmqpDriver

### ISSUE THREAD

**Issue by MichaelHindley** [bernardphp/bernard#243]
Spent quite some time trying to figure out why this code doesn't work as expected:

``` php
        $driver->pushMessage('dsfdfg', 'hello'); # message shows up in queue
        dump($driver->countMessages('dsfdfg')); # 0
```

https://github.com/bernardphp/bernard/blob/master/src/Driver/PhpAmqpDriver.php#L71

The methods are literally empty and don't do anything, it's not only countMessages, but several methods are actually empty and merged to master branch.

Am I missing something here, is this by design?

**Comment by henrikbjorn** [comment]
Not sure if the driver supports getting the count, if it does, then feel free to open a PR and make it even better!

**Comment by rtuin** [comment]
Amqp itself does not support getting the number of messages currently in the queue so I did not implement it for the PhpAmqpDriver at the time. The same goes for listing queues.

The remaining empty methods (`peekQueue`, `removeQueue` and `info`) could be implemented if you have the need for them.

There are more drivers that have unimplemented methods, so at least it's consistent among them.
One way to make unimplemented driver features more visible is by making these methods throw a "not implemented" exception, but this would break backwards compatibility.

**Comment by sagikazarmark** [comment]
#224 would be a solution for this
