### ISSUE TITLE
Fix Limit 1 bug on 0.12.X tag

### ISSUE THREAD

**Issue by dardoguidobono** [bernardphp/bernard#244]
currently i am using silex + bernardphp and doctrine. 
The bug of a missing space in 
protected function doPopMessage($queueName)
is fixed on the 1.X branch but not on the 0.12.

Thks.

**Comment by byhoratiss** [comment]
Yes, I'm experimenting the same issue. But using through BernardphpBundle, which installed <1.0 branch of bernardphp.

**Comment by sagikazarmark** [comment]
Fixed in https://github.com/bernardphp/bernard/commit/b0d3efa6530cb2d8010ae786a5fc1b8406a7fbed
