### ISSUE TITLE
documentation on persistence consumer runner

### ISSUE THREAD

**Issue by cordoval** [bernardphp/bernard#248]
is there a way to ensure ```php public/index.php consume algorithm-one``` keeps running all the time? I mean without supervisord or some other stuff, would be interest hearing what you guys are using out there.

My worry is what happens if the consumer crashes who will be responsible of bringing it back up? It is left out from the documentation but a at least a pointer would be helpful.

**Comment by henrikbjorn** [comment]
It is your responsibility to make sure if it crashes to get it backup. For this you can use Supervisord or a similar system. Most UNIX/Linux based systems have these build in as well. 

Feel free to open a PR with a note with information about doing this.
