### ISSUE TITLE
bernard with supervisord

### ISSUE THREAD

**Issue by cordoval** [bernardphp/bernard#253]
i am having a weird issue with bernard, when i run the command to consume manually on the console it works fine, however when i tell supervisord to run things, supervisord still works ok, but the php process is stopped and does not continue/finish == no logs to debug.

here is my conf:

```
[program:algorithmOne]
command=/usr/bin/php index.php consume algorithm-one
process_name=%(program_name)s
numprocs=1
directory=/tmp
priority=999
autostart=true
autorestart=true
startretries=3
stopwaitsecs=180
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=25MB
```

any hints on what could be happenign or how to go around it?

**Comment by henrikbjorn** [comment]
I have no idea.

**Comment by cordoval** [comment]
supervisord works waiting for signals and stuff, so i think the problem is on the implementation on the bind perhaps https://github.com/bernardphp/bernard/blob/master/src/Consumer.php#L168

**Comment by cordoval** [comment]
@henrikbjorn i am going to try forking it and removing those signal stuff, according to the docu it says windows does not use that. So i think even in linux or unix it can work without those lines right? just checking before wasting my time trying 👍

**Comment by henrikbjorn** [comment]
We use them on linux to do a clear shutdown when interrupting and so on. So they can't be removed.

**Comment by cordoval** [comment]
I see i am trying with them removed. After this if things still don't work i will switch to rabbitmq, hope not, but i gotta get this done 😊

**Comment by henrikbjorn** [comment]
@cordoval did you figure it out, or did you abandon it?

**Comment by cordoval** [comment]
i am close to abandoning it, weird behaviors lots of problems very critical project

**Comment by cordoval** [comment]
I have ditched supervisord for cron script to check it

i am now trying to split queues, i need to avoid that multiple runs of the command take the same $message->id, so that they actually collaborate and not collide.

**Comment by henrikbjorn** [comment]
Multiple consumer will by default not collide and do the same work twice. Also your messages should not result in side effect and always have the same result.

**Comment by cordoval** [comment]
yes it is weird, not sure why they do such a thing.

**Comment by henrikbjorn** [comment]
What driver do you use, and what kind of work do your Receivers do ?

**Comment by cordoval** [comment]
Doctrine driver. the work is a O(n2) job. The work is with an $message->id, it is idempotent the first algorithm but not the second since it depends on the results of the second algorithm. In reality is never idempotent since it will depend on the database values. Ideally the idea is that if there is a queue with messages that the workers will take one and if there is another consumer it will not be doing the same job but the next in the queue.

**Comment by henrikbjorn** [comment]
Can you reproduce this in some way, maybe start two consumers, and log the messages they work on, it should be easy to spot duplicates.

**Comment by kynx** [comment]
This ticket has strayed a bit from the original title, but FWIW I'm running bernard under supervisord just fine. It's dockerized, so the config does some funny stuff with the logs, but here's what I've got in /etc/supervisord.conf:

```
[supervisord]
logfile=/dev/null
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:queue-consumer]
command=/var/lib/myapp/console.php bernard:consume myqueue
directory=/var/lib/myapp
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
auto_start=true
autorestart=true
user=console
```

Hope that helps anyone who stumbles on this ticket.

**Comment by acrobat** [comment]
I'm going to close this ticket as the original problem is abandoned. If anyone experiences issues with supervisor please open a new issue!

**Comment by cordoval** [comment]
This is fine, i am no longer using bernard for multiprocessing and i am no longer working on that project either. 👍
