### ISSUE TITLE
Separate routers to smaller packages

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#258]
I am not so sure about this as in case of drivers, but could be a possibility too.

**Comment by acrobat** [comment]
I don't think the routers need to moved to separate packages. For the drivers this is indeed a "natural" choice, but don't need this approach IMHO

**Comment by sagikazarmark** [comment]
In my opinion everything that has an external dependency should be removed from the core library. Optional dependencies destroy the whole point of having dependencies IMO and should be avoided whenever possible. In an optimal case we can have at least a few implementations of drivers and routers which does not have an external dependency, so the core library remains functional.

**Comment by sagikazarmark** [comment]
Most of the vendor container routers are going to be removed, so this can be closed.
