### ISSUE TITLE
OpenCloud driver

### ISSUE THREAD

**Issue by kynx** [bernardphp/bernard#266]
I've written a driver for [php-opencloud](https://github.com/rackspace/php-opencloud/) which I'd like to send a PR for. But I've got a couple of questions...

1. Looking at the Doctrine driver, if you `pushMessage()` to a non-existent queue it'll get created for you. But it doesn't look like SQS or IronMQ work that way (though I'm not at all familiar with the underlying API). What's right?
2. By default the php-opencloud API doesn't return the client's own messages when listing them, but looking at the Doctrine driver's `peekQueue()` I think it probably should. Is that right?
3. ~~The tests I've got require a Rackspace account. I don't like mocking what I don't know, but I guess I could skip them if an account isn't available and add some mocks. What's the best approach here?~~

Thanks!

**Comment by kynx** [comment]
OK, I'm converting the tests to use Guzzle's MockPlugin to simulate the responses from the API. That way at least the php-opencloud touch points get tested.

**Comment by kynx** [comment]
My code is available over [here](https://github.com/kynx/bernard-opencloud). I'd do a PR right away, but I'm beginning to think this would be better in a separate repository (as maybe would the other drivers?). There are a couple of reasons:

* The current stable version php-opencloud has a dependency on Guzzle 3, which creates an ugly warning in composer
* Version 2 of php-opencloud is in the works, but [not progressing quickly](https://github.com/rackspace/php-opencloud/issues/691). It looks to be PHP7+, as opposed to Bernard's 5.4+
* I'd like to have a go at creating a v2 version, but that would be much easier in a separate repo

@henrikbjorn - what are your thoughts? I'll do a PR against this repo if you want. Or if you think a separate repo is a good idea, create one and I'll do a PR against that. Cheers!

**Comment by henrikbjorn** [comment]
Hey @kynx 

I created https://github.com/bernardphp/OpenCloud for you.

**Comment by kynx** [comment]
Awesome! PR is at https://github.com/bernardphp/OpenCloud/pull/1

**Comment by sagikazarmark** [comment]
Moving to bernardphp/drivers#12
