### ISSUE TITLE
Serializers documentation

### ISSUE THREAD

**Issue by kynx** [bernardphp/bernard#272]
It looks like [serializers.rst](https://github.com/bernardphp/bernard/blob/master/doc/serializers.rst) is out of date. I can do a PR with what works for me, which isn't much more than:

```
$serializer = new Serializer(new AggregateNormalizer([
    new EnvelopeNormalizer(),
    new GetSetMethodNormalizer(),
    new DefaultMessageNormalizer(),
]));
```

But I'm not sure what to do with the Symfony and JMS serializer stuff. Are they even still needed?

**Comment by henrikbjorn** [comment]
Seems right, no JMS Serializer is not needed anymore. Everything goes through symfony's serializer component.
