### ISSUE TITLE
Common exceptions for drivers

### ISSUE THREAD

**Issue by kynx** [bernardphp/bernard#276]
It'd be good to have a common set of exceptions implementing something like `Bernard\Exception\ExceptionInterface` for the drivers. Right now users have to catch exceptions thrown by the underlying implementation, so switching drivers would involve re-writing code.

Off the top of my head:

```
class ServiceUnavailableException extends \RuntimeException implements ExceptionInterface
{}

class QueueNotFoundException extends \RuntimeException implements ExceptionInterface
{}

class NotImplementedException extends \BadMethodCallException implements ExceptionInterface
{}

class InvalidArgumentException extends \InvalidArgumentException implements ExceptionInterface
{}
```

Thoughts?

**Comment by henrikbjorn** [comment]
Sounds great
