### ISSUE TITLE
SQSDriver::createQueue() and SQSDriver::removeQueue() not implemented?

### ISSUE THREAD

**Issue by holtkamp** [bernardphp/bernard#280]
Just wondering, is there a particular reason the the SQSDriver seems incomplete?

- [SQSDriver::createQueue()](https://github.com/bernardphp/bernard/blob/7949ba87a1c58f8dd4c17120f4f24acd4df764e3/src/Driver/SqsDriver.php#L58-L60)
- [SQSDriver::removeQueue()](https://github.com/bernardphp/bernard/blob/7949ba87a1c58f8dd4c17120f4f24acd4df764e3/src/Driver/SqsDriver.php#L146-L148)

Might be better to throw an "Not Yet Implemented" exception instead of doing 'nothing'?

**Comment by henrikbjorn** [comment]
A PR would be great :)

**Comment by holtkamp** [comment]
ok, will give it a shot, maintaining proper test coverage will be the hard part I guess 😊

**Comment by holtkamp** [comment]
Resolved by https://github.com/bernardphp/bernard/pull/281
