### ISSUE TITLE
Tidy up requirements.

### ISSUE THREAD

**Issue by henrikbjorn** [bernardphp/bernard#283]
Remove support for old php versions, old doctrine versions etc.

**Comment by sagikazarmark** [comment]
Should this involve dropping PHP 5.6 support as well? Honestly after the long struggle Bernard survived, I believe it deserves a release supporting PHP 5.x. There are still a lot of us stuck on that version.

**Comment by sagikazarmark** [comment]
Yeah, same thoughts, but I'm not sure dropping PHP 5.6 support in a minor adds too much. We can't change the interfaces to have scalar type hints and return values in a minor release.

**Comment by acrobat** [comment]
No we can't really use any new php7 features until the next major. But supporting old and eol php versions is not necessary imo.

**Comment by sagikazarmark** [comment]
Okay, that's a question for later, for now we keep PHP 5.6 then.
