### ISSUE TITLE
gracefully shutdown consumer

### ISSUE THREAD

**Issue by trongdong** [bernardphp/bernard#291]
Hi there, 
First of all, thanks for such a great library.  
At the moment, we use bernard with redis driver for our job queue. The consumer is running under supervisord. 
Our job is a bit heavy and it would take around 30 secs to process each message. And the message need to call multiple binary as child process.  
We're facing an issue that whenever we need to deploy new code, we need to restart the consumer and it would make the job fails, which is unacceptable.  
Is there any way to gracefully shutdown the consumer? We need to avoid the consumer to receive new job, wait for the current job done and then restart.  

Thanks in advanced!

**Comment by bendavies** [comment]
this is exactly what the consumer currently does.
signals are caught:
https://github.com/bernardphp/bernard/blob/master/src/Consumer.php#L170
which causes the consumer to shutdown after the current job has finished processing

**Comment by henrikbjorn** [comment]
make sure you are sending the correct signal and not just killing it off.

**Comment by trongdong** [comment]
Thanks for your answer. I know that line of code and sent the correct signal. However, I notice that our consumer spawn a new child process (wkhtml2pdf for example), and when the signal is sent, it kill sub process immediately.

**Comment by henrikbjorn** [comment]
@trongdong Have you tested that wkhtml2pdf arent forking on its own and catching the signal and then terminating the job?

Bernard does not fork out a process per job.

**Comment by trongdong** [comment]
@henrikbjorn At the moment, we use symfony process to fork new process. I think that the child process are catching that signal as well. Anyway, this is our problem but not bernard.
