### ISSUE TITLE
Fatal error: Call to undefined method Container::isRegistered() in /var/www/rise.global/vendor/bernard/bernard/src/Router/LeagueContainerAwareRouter.php on line 40

### ISSUE THREAD

**Issue by paolooo** [bernardphp/bernard#292]
**Fatal error: Call to undefined method Container::isRegistered() in /var/www/rise.global/vendor/bernard/bernard/src/Router/LeagueContainerAwareRouter.php on line 40**

\# | Time | Memory | Function | Location
-- | ----- | ------- | --------- | ----------
.. | ... | ... | ... | ...
6 | 1.0987 | 11823752 | Bernard\Router\LeagueContainerAwareRouter->accepts( ) | .../SimpleRouter.php:33

**Comment by acrobat** [comment]
Fixed in #293
