### ISSUE TITLE
Invalid if statament in SimpleRouter

### ISSUE THREAD

**Issue by vova07** [bernardphp/bernard#300]
https://github.com/bernardphp/bernard/blob/master/src/Router/SimpleRouter.php#L47 I think it should be `if (null == $receiver) {` because this https://github.com/bernardphp/bernard/blob/master/src/Router/SimpleRouter.php#L75 return `null` when there are no receiver. 
Because of that was really hard to understand what is going on.

Thanks!

**Comment by henrikbjorn** [comment]
In theory you are correct, in practice it does not really matter as `null == false` will evaluate to `true`.

``` bash
php -r 'var_dump(null == false);'
bool(true)
```

However if you want to do a PR i will happily merge it.
