### ISSUE TITLE
Syncronous queue

### ISSUE THREAD

**Issue by mnvx** [bernardphp/bernard#301]
I use this nice library in my project for workers, parallel task execution.

All is very good, but for development and tests would be great to have way of run tasks in syncronous queue. It is more handy for debug. I would not run consumers, tasks would executed immediately as soon as they would have in queue.

For example, this approach realised in [Laravel](https://github.com/illuminate/queue/blob/a1e16ecd7faf25d9cd992426efe8c69a14f5c035/SyncQueue.php).

Would be great to have syncronous queues in Bernard too.

**Comment by makasim** [comment]
Synchronous queue is not that good idea as it might look like. 

It works in the context of your current process. In sync queue the consumer may access a currently logged in user for example. You can even write a test and it would work but you face the error once you go live and use something real (like RabbitMQ). If you want to test it do it separately.Some tests for producer and others for consumer.
Other example. The mailer throws an exception and in sync queue it crashes the whole process. You do not want that so you add a try .... catch but in reality it is not needed at all.

Queue async by its nature with its benefits and surprises. The concurrency is very high so you might need locks. There is nothing like that when you do stuff one after another. Again you might realize you have problems too late.

**Comment by mnvx** [comment]
@makasim I agree with your arguments against syncronous queue. But in practice there is a sense in syncronous queue. Any more examples:

* I use queues in project, what using in many different companies: from very large where parallel processing of tasks is really needed to very small with weak it specialists where small data flows and it is not necessary to install server of queues and run consumers in background. 
* Project, where I use Bernard library, supporting by specialist with very different level of education and parallelism and requirement to install queue server will up entry level into project. So, it is good idea to provide more easy way with syncronous queue.

And of course it is always possible to replace SyncQueue with PersistentQueue using service provider. And it is choise of developer - to use syncronous queue or not. I just propose possibility of this choice.

**Comment by henrikbjorn** [comment]
@mnvx Instead of executing the Queue instantly when you enqueue a message it would be better to use the consumer and give it the InMemoryQueue instead.

**Comment by mnvx** [comment]
@henrikbjorn Thanks for reply. I saw InMemoryQueue, but this way require to use consumers. SyncQueue not require to use consumers. This way more preffer if I want to make entry level into my project (with queues) more easy.

**Comment by henrikbjorn** [comment]
The problem with this is that you may introduce a lot of latency in your application. Also you are sidestepping the logic. If we merge this we have to maintain the same logic in the consume as in the Queue it self.

If you want to, you can do a Producer that takes a Consumer and executes a single event on every produce.

**Comment by mnvx** [comment]
I did it with custom producer class. Thanks for good advice.

```php
use Bernard\Consumer;
use Bernard\Message;
use Bernard\Producer;
use Bernard\QueueFactory;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class ConsumingProducer extends Producer
{
    /**
     * @var Consumer
     */
    protected $consumer;

    /**
     * ConsumingProducer constructor.
     * @param QueueFactory $queues
     * @param EventDispatcherInterface $dispatcher
     * @param Consumer $consumer
     */
    public function __construct(QueueFactory $queues, EventDispatcherInterface $dispatcher, Consumer $consumer)
    {
        parent::__construct($queues, $dispatcher);
        $this->consumer = $consumer;
    }

    /**
     * @inheritdoc
     */
    public function produce(Message $message, $queueName = null)
    {
        parent::produce($message, $queueName);
        $this->consumer->tick($this->queues->create($queueName));
    }
}
```
