### ISSUE TITLE
FlatFileDriver::removeQueue() fails when jobs have failed

### ISSUE THREAD

**Issue by kynx** [bernardphp/bernard#303]
Hi,

This is coming up in my test environment. If a receiver throws an exception, the message is left in the queue directory with a name like '123.job.proceed'. `removeQueue()` only removes files that match `#\.job$#`, so the subsequent call to `rmdir()` fails.

What would be the best solution here? It would be easiest if `removeQueue()` also removed the *.proceed messages. But maybe it would be better if the file were removed via a custom `FailureSubscriber`? What would match the behaviour of other drivers the best?

**Comment by henrikbjorn** [comment]
removeQueue should remove files with the .proceed extension as well :) as the file queue is only really for testing etc.

**Comment by acrobat** [comment]
Fixed in #305
