### ISSUE TITLE
Attempted to load class "DefaultMessageNormalizer" from namespace "Bernard\Normalizer"

### ISSUE THREAD

**Issue by bushibigniu** [bernardphp/bernard#304]
the DefaultMessageNormalizer is not found, but in symfony code is:
return $this->services['bernard.normalizer.default_message'] = new \Bernard\Normalizer\DefaultMessageNormalizer();
so,throw error.
my symfony version is 3.2.7.
my project composer.json write is "bernard/bernard": "1.0.*@dev",
        "bernard/bernard-bundle" : "~2.0"

the detail error is :
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DefaultMessageNormalizer" from namespace "Bernard\Normalizer".
Did you forget a "use" statement for another namespace? in /var/cache/dev/appDevDebugProjectContainer.php:833
Stack trace:
#0 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(310): appDevDebugProjectContainer->getBernard_Normalizer_DefaultMessageService()
#1 /var/cache/dev/appDevDebugProjectContainer.php(4892): Symfony\Component\DependencyInjection\Container->get('bernard.normali...')
#2 /var/cache/dev/appDevDebugProjectContainer.php(781): appDevDebugProjectContainer->getBernard_QueueFactoryService()
#3 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(310): appDevDebugProjectContainer->getBernard_Command_ConsumeService()
#4 /vendor/berna in /var/cache/dev/appDevDebugProjectContainer.php on line 833

please,can you help me?

**Comment by henrikbjorn** [comment]
Seems like you install have failed for some reason. Try and be more explicit with the version for bernard. The latest release for the upcoming 1.0.0 release is `1.0.0-alpha4`

**Comment by dndam** [comment]
Same issue! As mentioned above try installing 1.0.0-alpha4 version
`composer require bernard/bernard:1.0.0-alpha4`

This solved the issue on my end. Also, if you have a look to the src/Normalizer namespace you'll observe that indeed DefaultMessageNormalizer is no longer available. However, in alpha4 version this is present

**Comment by henrikbjorn** [comment]
It have since 1.0.0-alpha4 been renamed `PlainMessageNormalizer`.

**Comment by acrobat** [comment]
This should be fixed with the latest release 1.0.0-alpha5 and the 2.0.1 release of the BernardBundle
