### ISSUE TITLE
Example does not work (checked doctrine - probably for any driver) 

### ISSUE THREAD

**Issue by GregPK** [bernardphp/bernard#313]
When running any file from `example/` you will get the following error:

```
Catchable fatal error: Argument 1 passed to Bernard\EventListener\FailureSubscriber::__construct() must be an instance of Bernard\Producer, instance of Bernard\QueueFactory\PersistentFactory given, called in ./example/bernard.php on line 67 and defined in ./vendor/bernard/bernard/src/EventListener/FailureSubscriber.php on line 21
```

The line at fault is this one: https://github.com/bernardphp/bernard/blob/master/example/bootstrap.php#L34. When it's removed - runs fine.

**Comment by acrobat** [comment]
@GregPK thanks for reporting the issue! Can you please check if #314 fixes your issue? Thanks!
