### ISSUE TITLE
Compatibility with mongodb php7 extension

### ISSUE THREAD

**Issue by acrobat** [bernardphp/bernard#316]
mongodb has a new php7 extension. This is a minimal api and a userland library (https://github.com/mongodb/mongo-php-library) is provided to have all classes available

But this will break some typehints in our code, like https://github.com/bernardphp/bernard/blob/master/src/Driver/MongoDBDriver.php#L23

mongodb tests are currently skipped on php7

**Comment by sagikazarmark** [comment]
We probably have to create two separate drivers then.

**Comment by acrobat** [comment]
Yes indeed, that will be the best solution. Let's first do the split of the current drivers and then see what we can do for the mongodb driver

**Comment by sagikazarmark** [comment]
Moving to bernardphp/drivers#11
