### ISSUE TITLE
Support for AWS SQS FIFO Queues

### ISSUE THREAD

**Issue by holtkamp** [bernardphp/bernard#317]
[AWS SQS supports FIFO Queues](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html), which could be nice for asynchronous event processing  when the order of the events is important to maintain.

Important aspects:
- a FIFO QueueName always ends with suffix `.fifo`
- when creating a FIFO Queue, an attribute `FifoQueue` is required
- when sending a message, additional attributes are required: 
 - `MessageGroupId` to indicate the 'origin' of the message
 - `MessageDeduplicationId` to identify the content of the message

More details in [this blog post](https://aws.amazon.com/blogs/developer/how-the-amazon-sqs-fifo-api-works/)

**Comment by acrobat** [comment]
Fixed in #318
