### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by slince** [bernardphp/bernard#325]
Hi there, i have some questions. 
1. Is there any plan to release a stable version?
2. How to track the message status.

**Comment by acrobat** [comment]
Yes I think the rough plan of @sagikazarmark was to have a stable release by the end of the year. The biggest task will be splitting the drivers out of this repo and into separate packages.

About the message status can you explain a bit more what you are trying to do?

**Comment by slince** [comment]
@acrobat 

> About the message status can you explain a bit more what you are trying to do?

Ok, sometimes we need to tell client whether to wait or try again. So we have to track a job status(waiting, completed or failed)

**Comment by slince** [comment]
> The biggest task will be splitting the drivers out of this repo and into separate packages.

I don't think you need to do that. Reference [monolog](https://github.com/Seldaek/monolog/tree/master/src/Monolog/Handler), it have so many drivers.

**Comment by acrobat** [comment]
I don't know which queue driver you use, but for example the flatfile driver. All messages in the directory are waiting, but when they have the .proceed suffix they are currently being processed and when the file is not in the directory the job is completed (failed jobs are still in the directory, just like a new job)

About the driver separation process, this is indeed something that is not necessary. But all the drivers create "soft dependencies" (composer suggests). By moving the drivers to separate packages when are able to declare "hard" dependencies on the required libs. See #256 for the full discussion on this topic.
