### ISSUE TITLE
Infinite recursion in example

### ISSUE THREAD

**Issue by marulitua** [bernardphp/bernard#335]
function get_event_dispatcher will call function get_producer to get an instance of Producer,
```
function get_event_dispatcher() {
    $dispatcher = new EventDispatcher;
    $dispatcher->addSubscriber(new EventListener\ErrorLogSubscriber);
    $dispatcher->addSubscriber(new EventListener\FailureSubscriber(get_producer()));
    return $dispatcher;
}
```
in order to generate instance producer function get_producer will call function get_event_dispatcher to generate an instance of EventDispatcher.

```
function get_producer() {
    return new Producer(get_queue_factory(), get_event_dispatcher());
}
```
This leads to infinite recursion when run example with any driver.

**Comment by sagikazarmark** [comment]
Thanks for reporting. Fixed in https://github.com/bernardphp/bernard/commit/c554419d7971c70055ae4c541f307dd2ec1fff01
