### ISSUE TITLE
Does bernard support parallel tasks?

### ISSUE THREAD

**Issue by SlimDeluxe** [bernardphp/bernard#351]
I can't find it in the docs - is it possible to run two or more tasks in parallel?
E.g. I use a producer to queue task A which takes 10 seconds, and immediately task B which takes 1 second.
Will they be executed one after the other or is there a way to unblock task B and let it finish earlier?

I want to do something like this:

```
		$factory = new PersistentFactory($this->get_driver(), new SimpleSerializer());
		$producer = new Producer($factory, new Middleware\MiddlewareBuilder);

		$message = new DefaultMessage('PrepareReport', array(
			'report_id' => 12,
		));

		$producer->produce($message);

		$message2 = new DefaultMessage('SendEmail', array(
			'email_id' => 12,
		));

		$producer->produce($message2);
```
... where SendEmail takes 1 second so I don't want to block it.

**Comment by kynx** [comment]
The consumer will process one message at a time. If you want them running in parallel, launch multiple consumers.

**Comment by SlimDeluxe** [comment]
I think "Roundrobin queue" is what I was looking for but didn't really notice it before. Anyway there's no reference for it in code so I guess it was removed.
Thank you for your reply.
