### ISSUE TITLE
Create a Dockerfile for running tests locally

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#357]
- [x] Create `bernardphp` organization

**Comment by henrikbjorn** [comment]
Please invite to it :)

**Comment by sagikazarmark** [comment]
Username?

**Comment by sagikazarmark** [comment]
@henrikbjorn can you give me access to [Scrutinizer](https://scrutinizer-ci.com/g/bernardphp/bernard/) please?

**Comment by henrikbjorn** [comment]
@sagikazarmark "henrikbjorn" sure, i'll look into it.

**Comment by sagikazarmark** [comment]
This shouldn't block the release.
