### ISSUE TITLE
Check why Travis does not report commit status

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#364]
@henrikbjorn can you please check this? I can't see the registered hooks.

(Scrutinizer also does not report status upon PRs, nor uses the uploaded code coverage reports)

**Comment by sagikazarmark** [comment]
@henrikbjorn can I ask more access to the org? I would like to setup subtree splitting and travis

**Comment by sagikazarmark** [comment]
Ping @henrikbjorn

**Comment by sagikazarmark** [comment]
Ping @henrikbjorn

**Comment by henrikbjorn** [comment]
Hey. Sorry i must have missed this issue. It seems that i have to make you an Owner in order to give you more access. What access are you missing?

**Comment by sagikazarmark** [comment]
I would like to enable subtreesplit.com and scrutinizer integration for the drivers repo and probably readd travis integration, because commit status is not reported.

**Comment by henrikbjorn** [comment]
It seems subtree split was under some requested thing. I approved it. I can remove travis if you want to readd it. I might need to give up on my control gene :)

**Comment by sagikazarmark** [comment]
Not relevant anymore: switched to GitHub Actions.
