### ISSUE TITLE
Drop AppEngine driver?

### ISSUE THREAD

**Issue by sagikazarmark** [bernardphp/bernard#376]
Is it still useful? IMO Google PubSub would be a better path to follow. Not a single issue arrived for this driver over the years and it can always be added back if someone needs it.

**Comment by henrikbjorn** [comment]
PubSub is not suitable for message queues

**Comment by henrikbjorn** [comment]
Unless it works like NSQ

**Comment by sagikazarmark** [comment]
Moving it to the drivers package then.
