### ISSUE TITLE
How to dequeue messages once they are added to a queue?

### ISSUE THREAD

**Issue by robskrob** [bernardphp/bernard#397]
I'm trying to have my consumer process -- `php worker.php consume` -- just dequeue a message when a producer enqueues a message on the queue: `php worker.php produce`.

I cannot seem to see any activity where [I expect](https://github.com/robskrob/bernard-example/blob/master/worker.php#L19) it to, and I am guessing it has something to do with registering the right dispatcher event. For this very simple behavior that I am looking for -- the consumer process dequeueing a message once a message is added to the queue from producer -- do I have to add the `EventListener\LoggerSubscriber()` as a subscriber to the instance of my `EventDispatcher` ? If so, can you provide an example as to how to use `EventListener\LoggerSubscriber()`?

I have a toy example [here](https://github.com/robskrob/bernard-example/blob/master/worker.php), and [this is where](https://github.com/robskrob/bernard-example/blob/master/worker.php#L53) I am guessing I would add the additional subscriber, but I am not too sure how to set up this subscriber.

**Comment by henrikbjorn** [comment]
You are mapping a named message called `product` with lower case, but you are creating a `Product` message.

**Comment by robskrob** [comment]
@henrikbjorn thank you very much for pointing that out. Indeed, the named message mapping and and the name of the message were not the same. On top of that I was creating a queue `$queues->create('product-service')` -- when it needed to be `$queues->create('product')`

**Comment by robskrob** [comment]
I'll close the issue because now my consumer process is picking jobs off the redis queue when the producer enqueues a message.

**Comment by henrikbjorn** [comment]
Personally I like the https://github.com/bernardphp/bernard/blob/master/src/Router/ClassNameRouter.php
