### ISSUE TITLE
Are there wordpress examples?

### ISSUE THREAD

**Issue by robskrob** [bernardphp/bernard#399]
Are there any examples or guidelines for installing bernard on wordpress?

I've been able to set up the consumer, waiting to dequeue messages from Redis. However, enqueueing a job onto Redis with a bernard Producer has been challenging.

**Comment by henrikbjorn** [comment]
Sorry, there are no examples. But creating a Producer and sharing that between Wordpress services shouldn't be that hard.

**Comment by robskrob** [comment]
@henrikbjorn thank you for letting me know. I was able to get bernard setup on wordpress. Maybe when I finalize things on my side, I can share an example, setting up bernard on wordpress -- if that would be helpful.
