### ISSUE TITLE
How many messages can Bernard take off queue at once?

### ISSUE THREAD

**Issue by robskrob** [bernardphp/bernard#400]
With sidekiq I know that the number of threads (https://github.com/mperham/sidekiq/wiki/Advanced-Options#concurrency) available to the sidekiq process determines how many concurrent workers I can have at any given moment. In other words if I specify 5 concurrent threads to my sidekiq process I know that at any given moment a sidekiq process can take 5 messages off of the redis queue to work on. 

Does Bernard work in a similar way? How many messages can be taken off a redis  queue in a given moment? Do I have control over the amount of messages the Bernard process works in at any given moment?

**Comment by sagikazarmark** [comment]
PHP is (usually) single threaded, and even though there are certain concurrency solutions for it, a single worker will always work on a single message in case of Bernard. So essentially, the number of running workers determine the number of messages being worked on. There is no other limitation in Bernard.

Obviously, the real bottleneck is the message broker you use, but it would require a lot of PHP processes to reach the throughput limit of redis for example.

**Comment by sagikazarmark** [comment]
Yup, but it's probably better to call consumers what you call "bernard processes".

**Comment by robskrob** [comment]
@sagikazarmark thank you for sharing all this  information. I can close the issue.
