### ISSUE TITLE
Cannot instantiate interface Bernard\Serializer

### ISSUE THREAD

**Issue by robskrob** [bernardphp/bernard#402]
I'm using `bernard`, `0.13.0`.

Whenever I execute [my function](https://github.com/robskrob/bernard-example/blob/feature/wordpress-sample/background-logic/consumer.php#L23) to get the queue factory, the following error is raised:
```
php background-logic/consumer.php consume
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Bernard\Serializer in /Users/robskrob/code/scrap/bernard-toy/background-logic/message-queue.php:20
Stack trace:
#0 /Users/robskrob/code/scrap/bernard-toy/background-logic/consumer.php(23): MessageQueue->getQueueFactory()
#1 /Users/robskrob/code/scrap/bernard-toy/background-logic/consumer.php(58): consume()
#2 /Users/robskrob/code/scrap/bernard-toy/background-logic/consumer.php(62): main()
#3 {main}
  thrown in /Users/robskrob/code/scrap/bernard-toy/background-logic/message-queue.php on line 20
```

Why can I not instantiate `Bernard\Serializer` [here](https://github.com/robskrob/bernard-example/blob/feature/wordpress-sample/background-logic/message-queue.php#L20)?

**Comment by henrikbjorn** [comment]
You are using the example from master and not the example from 0.13 (or we haven't updated the example).

In 0.13 you can use one of the implementations `https://github.com/bernardphp/bernard/blob/0.13.0/src/Bernard/Serializer/SimpleSerializer.php`

**Comment by robskrob** [comment]
@henrikbjorn thank you for sharing `SimpleSerializer`. Also, per version I will check [this example](https://github.com/bernardphp/bernard/blob/0.13.0/example/bootstrap.php).
