### ISSUE TITLE
Incompatible with Symfony 4.3

### ISSUE THREAD

**Issue by holtkamp** [bernardphp/bernard#404]
As of Symfony 4.3, the signature of the EventDispatcher has changed: https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

This causes an error of type `E_USER_DEPRECATED` to be triggered: bundle:
```
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead. in /app/vendor/symfony/event-dispatcher/EventDispatcher.php:58
```
also see: 

https://github.com/symfony/event-dispatcher/blob/v4.3.3/EventDispatcher.php#L58

Maybe we can prevent this error by restricting the version of the used Symfony Event-Dispatcher in [`composer.json`](https://github.com/bernardphp/bernard/blob/eab0f25453657aa5e0b5efa01df1e0584a2a24a9/composer.json#L12) to `"symfony/event-dispatcher": "^3.0 || <4.3"`:

`

**Comment by sagikazarmark** [comment]
Well, this is just a deprecation warning, so I don't there is anything we have to do. If you are concerned about this error, just don't install 4.3. :)

**Comment by acrobat** [comment]
Like @sagikazarmark already said this is indeed a warning and shouldn't be a problem until symfony 5.0. But we can already fix our code to not trigger this deprecation on version of symfony that support the new way of dispatching events.

If you want @holtkamp you can open a PR to provide a backwards compatible fix for this deprecation, otherwise this will be fixed in the future when I have some time!

**Comment by holtkamp** [comment]
AFAIK the Symfony version is stored in [`Symfony\Component\HttpKernel\Kernel::VERSION_ID`](https://github.com/symfony/http-kernel/blob/v4.3.3/Kernel.php#L77) which is not used in Bernard, so we can not compare versions easily. 

However, as of `4.3` [`Symfony\Component\EventDispatcher\EventDispatcherInterface`](https://github.com/symfony/event-dispatcher/blob/v4.3.0/EventDispatcherInterface.php#L23) extends the [`Symfony\Contracts\EventDispatcher\EventDispatcherInterface`](https://github.com/symfony/event-dispatcher-contracts/blob/master/EventDispatcherInterface.php). 

Essentially the dispatch() method has changed from:

[`Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch($eventName, Event $event = null)`](https://github.com/symfony/event-dispatcher/blob/4.2/EventDispatcherInterface.php#L34)

to

[`Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch($event/*, string $eventName = null*/)`](https://github.com/symfony/event-dispatcher-contracts/blob/c43ab685673fb6c8d84220c77897b1d6cdbe1d18/EventDispatcherInterface.php)


@acrobat what do you think of the following approach to detect this new Interface to determine what to do?

```php 
class Producer
{
    /* ... properties and constructor can remain unchanged ...*/

    public function produce(Message $message, $queueName = null)
    {
        $queueName = $queueName ?: Util::guessQueue($message);
        $queue = $this->queues->create($queueName);
        $queue->enqueue($envelope = new Envelope($message));
        $this->dispatch(BernardEvents::PRODUCE, new EnvelopeEvent($envelope, $queue));
    }

    private function dispatch($eventName, EnvelopeEvent $event)
    {
        $this->dispatcher instanceof \Symfony\Contracts\EventDispatcher\EventDispatcherInterface)
           ? $this->dispatcher->dispatch($event, $eventName)
           : $this->dispatcher->dispatch($eventName, $event);
    }
}

**Comment by holtkamp** [comment]
Fixed in https://github.com/bernardphp/bernard/pull/406
