### ISSUE TITLE
PhpAmqpDriver not find in 0.13.0

### ISSUE THREAD

**Issue by victor-pilotto** [bernardphp/bernard#427]
Hi,

I'm trying update the bernard from dev-master to 0.13, but PhpAmqpDriver is not find.

Dont have support any more ?

Thanks.

**Comment by Baachi** [comment]
The bernard package has been splitted into multiple packages. For the amqp package you need to install the amqp package.

https://github.com/bernardphp/amqp-driver

**Comment by victor-pilotto** [comment]
Thanks Baachi, i'm didn't see this package
